{% set version = "3.0.1" %}

package:
  name: smmap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap/smmap-{{ version }}.tar.gz
  sha256: 171484fe62793e3626c8b05dd752eb2ca01854b0c55a1efc0dc4210fccb65446

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure git implementation of a sliding window memory map manager.'

extra:
    recipe-maintainers:
        - pelson
        - ocefpaf
