{% set name = "smmap" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smmap-{{ version }}.tar.gz
  sha256: dceeb6c0028fdb6734471eb07c0cd2aae706ccaecab45965ee83f11c8d3b1f62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - ez_setup
    - pip
    - wheel
  run:
    - python >=3.7

test:
  imports:
    - smmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gitpython-developers/smmap
  summary: A pure Python implementation of a sliding window memory map manager
  doc_url: https://pythonhosted.org/smmap/
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/gitpython-developers/smmap

extra:
   anaconda-services:
    reason: Dependency for apache-airflow
    recipe-maintainers:
      - ianaobi
