{% set name = "smmap" %}
{% set version = "5.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26ea65a03958fa0c8a1c7e8c7a58fdc77221b8910f6be2131affade476898ad5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A pure git implementation of a sliding window memory map manager.

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
