{% set version = "2.0.1" %}

package:
  name: smmap
  version: {{ version }}

source:
  fn: smmap-{{ version }}.tar.gz
  url: https://github.com/gitpython-developers/smmap/archive/v{{ version }}.tar.gz
  sha256: ff3df98fe1874228c5cae8c2cca18bf0122bbd1f8957eb2339f5faa61ffc4081

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - smmap
    - smmap.test

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure git implementation of a sliding window memory map manager.'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
