{% set name = "smmap" %}
{% set version = "5.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26ea65a03958fa0c8a1c7e8c7a58fdc77221b8910f6be2131affade476898ad5

build:
  skip: true  # [py<37 or py>312]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - smmap/test
  requires:
    - python
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv smmap/test
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pure git implementation of a sliding window memory map manager.
  description: |
    Smmap wraps an interface around mmap and tracks the mapped files as well as the amount of clients
    who use it. If the system runs out of resources, or if a memory limit is reached, it will
    automatically unload unused maps to allow continued operation.

    To allow processing large files even on 32 bit systems, it allows only portions of the file to
    be mapped. Once the user reads beyond the mapped region, smmap will automatically map the next
    required region, unloading unused regions using a LRU algorithm.

    Although the library can be used most efficiently with its native interface, a Buffer implementation
    is provided to hide these details behind a simple string-like interface.
    
    For performance critical 64 bit applications, a simplified version of memory mapping is provided
    which always maps the whole file, but still provides the benefit of unloading unused mappings on demand.
  dev_url: https://github.com/gitpython-developers/smmap
  doc_url: https://smmap.readthedocs.io

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
