package:
  name: smmap
  version: "0.9.0"

source:
  fn: smmap-0.9.0.tar.gz
  url: https://pypi.python.org/packages/source/s/smmap/smmap-0.9.0.tar.gz
  sha256: 0e2b62b497bd5f0afebc002eda4d90df9d209c30ef257e8673c90a6b5c119d62

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - smmap
    - smmap.test

about:
  home: https://github.com/Byron/smmap
  license: BSD License
  summary: 'A pure git implementation of a sliding window memory map manager'

extra:
    recipe-maintainers:
        - pelson
