{% set version = "3.0.4" %}

package:
  name: smmap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap/smmap-{{ version }}.tar.gz
  sha256: 9c98bbd1f9786d22f14b3d4126894d56befb835ec90cef151af566c7e19b5d24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A pure git implementation of a sliding window memory map manager.

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
