travis:
  secure:
    BINSTAR_TOKEN: AjiTcdMSoFM5R9Z/+p6d7iFwxCG9i1qHL3+ccOMpvoYz14Z9a4wVlq/TD5oGBAQ86NopSnFkzTUEHNnqYTmJ+n395EOEndoKdjZwnw37EbbxuneQnbptejljv+yCfho7l+VtzhaID3HjFfGzEBOTxfxNXDs6vkMks6i2AeIo1SLjbK29wMZlgOnEK0Cyxieq+brReo/wZot/BZzDV4EZAEiRuurU6AnNpToofUiQJMF2TXlmLGgGjWv7gJt3cXlPbER2Y2SOxl6/CxUYyG06aRzX4of2wmOEObESZIEIDHlRUeFzHsL4l/qonkGXE/SPgtnM3NyjYLMaCwJYEmrPDmMEqjClSgsfj4VcSpmu2eEFSGQ2M53O0371jnUqbZqO2HfIDIkNBpLyWvuLEUjXf51K2lyO25/ywjHGMzmzaZ+aJrNL6xPcLIzJvMJc4PzSzlYc+Ed0/PkreRsspgFDIah/rHDfq4z45ljpP9n83HAztD2tiirSpj/B2us01/37LuQSgzmcLMJ/myEjHjtXkyoWO6gZFTlJlilBrX0vsq3gXxmZzQ1g8zfZvrc1MnbH10JEw364fs1aT4VB1Xu3MlMXIlaxwLKkeVQm7dw5G7eDHPpgt0qInfKo+CwEr1AXfSw5+P0n9sr/chjUO/Cn2cpZPsq2+jdQlSljQc/i27E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
