travis:
  secure:
    BINSTAR_TOKEN: gebeLQTHEoCQxLddQUFhEQNub2x1vzzpZ0t5ibprUR6t8Fe+KNu65rksPnd4SqnKgDlIjZY846ebmXlnhPTH2kalR9oKJu6AFXHiACP0/hasw4Xes+ktG15gvJE53BYblc3JT/AaiwXb9I+G+cuwkGDPjpIMAHSULm/hMjIddmYKByKL00UqELjS79BaKbkyF5MNTYIXus7qNcyHD33aE4Z0yvWX8dBDmb5enr728yyiRAl4Ige6nWhrNMCkomtTtXkjXGlufq6RjNn1JwhJKpfYUwcScUmqRMARVKhubIcpM7girsyQ4wM6DP6nu9yTlozkTuBvVi4HbiWXSap5yeP5puE1InIyom/Mnk0oHg3nbzYaImsqA/RUwIn4+nAT4RuDozNe49NjnL+Pbx6cLmOZioFWy3MYWhCrLn9EsaGD6EX9nVhkHjd9O179iBjfGMLGb9FjDdC42ivbZxjTzbovudwgeAZFhQhVEL8nUHaknEYnJyfUXyeLhibThmDVSjrc0xmZEjVAbMRix5kdokPFPE2PQ6kgBlfySnMYeUfFh+kw6c34pqu3JeQE3lWlVkxRPrR+P10BhHlGEALX9zPyl+QcnfGrRUAuvw6b8GkrgZJNL+aeNmDUbT23VAU7IkyeF9fzrpVYDAdXPxVuabsnNmKOAG1DYmA+ubciBKg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: false
